List<Map<String, dynamic>> buildUpgradeMockProducts() {
  return [
    // Refrigerators
    {
      'id': 'p1',
      'brand': 'BOSCH',
      'name': 'Bosch French Door Refrigerator',
      'type': 'Refrigerator',
      'price': 3299,
      'discountPrice': 3074,
      'discount': 7,
      'rating': 4.7,
      'badges': ['Top Rated', 'Save 7%'],
      'features': [
        'VitaFresh Pro technology',
        'MultiAirflow system',
        'NoFrost technology',
      ],
      'monthlyPayment': 256,
    },
    {
      'id': 'p2',
      'brand': 'SAMSUNG',
      'name': 'Samsung 4-Door Flex Refrigerator',
      'type': 'Refrigerator',
      'price': 2499,
      'discountPrice': 2274,
      'discount': 8,
      'rating': 4.6,
      'badges': ['Best Seller', 'Save 8%'],
      'features': [
        'FlexZone™ customizable temperature drawer',
        'Twin Cooling Plus™ technology',
        'Ice & Water dispenser',
      ],
      'monthlyPayment': 190,
    },
    {
      'id': 'p3',
      'brand': 'LG',
      'name': 'LG InstaView Door-in-Door Refrigerator',
      'type': 'Refrigerator',
      'price': 2194,
      'discountPrice': 1974,
      'discount': 10,
      'rating': 4.5,
      'badges': ['Recommended', 'Save 10%'],
      'features': [
        'InstaView™ Door-in-Door®',
        'Craft Ice™ maker',
        'Smart ThinQ® technology',
      ],
      'monthlyPayment': 165,
    },
    {
      'id': 'p4',
      'brand': 'GE',
      'name': 'GE Profile French Door Refrigerator',
      'type': 'Refrigerator',
      'price': 2194,
      'discountPrice': 1974,
      'discount': 10,
      'rating': 4.5,
      'badges': ['New Arrival', 'Save 10%'],
      'features': [
        'Hands-Free AutoFill',
        'TwinChill™ evaporators',
        'WiFi Connect',
      ],
      'monthlyPayment': 165,
    },
    {
      'id': 'p5',
      'brand': 'Whirlpool',
      'name': 'Whirlpool French Door Refrigerator',
      'type': 'Refrigerator',
      'price': 1860,
      'discountPrice': 1674,
      'discount': 10,
      'rating': 4.4,
      'badges': ['Save 10%'],
      'features': [
        'Adaptive defrost',
        'Accu-Chill™ temperature system',
        'LED lighting',
      ],
      'monthlyPayment': 140,
    },
    {
      'id': 'p6',
      'brand': 'Frigidaire',
      'name': 'Frigidaire Gallery French Door Refrigerator',
      'type': 'Refrigerator',
      'price': 1860,
      'discountPrice': 1674,
      'discount': 10,
      'rating': 4.4,
      'badges': ['Save 10%'],
      'features': [
        'Smudge-Proof stainless steel',
        'PureAir Ultra® II filters',
        'Store-More™ shelves',
      ],
      'monthlyPayment': 140,
    },

    // Microwaves
    {
      'id': 'm1',
      'brand': 'Panasonic',
      'name': 'Panasonic Countertop Microwave (1.2 cu ft)',
      'type': 'Microwave',
      'price': 249,
      'discountPrice': 219,
      'discount': 12,
      'rating': 4.5,
      'badges': ['Best Seller', 'Save 12%'],
      'features': ['Sensor Cook', 'Inverter Technology', 'Quick 30 sec'],
      'monthlyPayment': 19,
    },
    {
      'id': 'm2',
      'brand': 'Whirlpool',
      'name': 'Whirlpool Over-the-Range Microwave (1.7 cu ft)',
      'type': 'Microwave',
      'price': 329,
      'discountPrice': 289,
      'discount': 12,
      'rating': 4.4,
      'badges': ['Top Rated', 'Save 12%'],
      'features': ['2-Speed Vent', 'LED Cooktop Light', 'Add 30 Seconds'],
      'monthlyPayment': 24,
    },
    {
      'id': 'm3',
      'brand': 'Samsung',
      'name': 'Samsung Ceramic Interior Microwave (1.1 cu ft)',
      'type': 'Microwave',
      'price': 279,
      'discountPrice': 249,
      'discount': 11,
      'rating': 4.3,
      'badges': ['Save 11%'],
      'features': ['Ceramic Enamel Interior', 'Eco Mode', 'Child Lock'],
      'monthlyPayment': 21,
    },

    // Dishwashers
    {
      'id': 'd1',
      'brand': 'BOSCH',
      'name': 'Bosch 300 Series Dishwasher',
      'type': 'Dishwasher',
      'price': 999,
      'discountPrice': 899,
      'discount': 10,
      'rating': 4.7,
      'badges': ['Top Rated', 'Save 10%'],
      'features': ['Quiet 44 dBA', 'AutoAir™ Dry', '3rd Rack'],
      'monthlyPayment': 75,
    },
    {
      'id': 'd2',
      'brand': 'GE',
      'name': 'GE Profile Dishwasher with Microban®',
      'type': 'Dishwasher',
      'price': 879,
      'discountPrice': 799,
      'discount': 9,
      'rating': 4.5,
      'badges': ['Best Seller', 'Save 9%'],
      'features': ['Dry Boost™', 'Piranha™ Hard Food', 'Sanitize Option'],
      'monthlyPayment': 67,
    },

    // Washing Machines
    {
      'id': 'w1',
      'brand': 'LG',
      'name': 'LG Front Load Washer (4.5 cu ft)',
      'type': 'Washing Machine',
      'price': 1099,
      'discountPrice': 999,
      'discount': 9,
      'rating': 4.6,
      'badges': ['Best Seller', 'Save 9%'],
      'features': ['TurboWash™', 'Steam™', 'SmartThinQ®'],
      'monthlyPayment': 84,
    },
    {
      'id': 'w2',
      'brand': 'Samsung',
      'name': 'Samsung Top Load Washer (5.0 cu ft)',
      'type': 'Washing Machine',
      'price': 899,
      'discountPrice': 829,
      'discount': 8,
      'rating': 4.4,
      'badges': ['Save 8%'],
      'features': ['Active WaterJet', 'Self Clean', 'Vibration Reduction'],
      'monthlyPayment': 69,
    },

    // Air Conditioners
    {
      'id': 'a1',
      'brand': 'Daikin',
      'name': 'Daikin 12,000 BTU Mini Split AC',
      'type': 'Air Conditioner',
      'price': 1899,
      'discountPrice': 1699,
      'discount': 11,
      'rating': 4.6,
      'badges': ['Top Rated', 'Save 11%'],
      'features': ['Inverter Compressor', 'Sleep Mode', 'Wi‑Fi Ready'],
      'monthlyPayment': 142,
    },
    {
      'id': 'a2',
      'brand': 'Carrier',
      'name': 'Carrier 10,000 BTU Window AC',
      'type': 'Air Conditioner',
      'price': 599,
      'discountPrice': 529,
      'discount': 12,
      'rating': 4.3,
      'badges': ['Save 12%'],
      'features': ['Energy Saver', 'Remote Control', '24‑hr Timer'],
      'monthlyPayment': 44,
    },
  ];
}
