/// Centralized string constants for the app.
/// ─────────────────────────────────────────────────────────────────────────────
/// **Single source of truth** – every screen must import this file instead of
/// hard-coding brand names, labels, or messages.
///
/// To rebrand the app, change ONLY the values in the "Brand / App Identity"
/// section below and everything updates automatically.
/// ─────────────────────────────────────────────────────────────────────────────
class AppStrings {
  AppStrings._();

  // ══════════════════════════════════════════════════════════════════════════
  //  BRAND / APP IDENTITY  — change here to rebrand the entire app
  // ══════════════════════════════════════════════════════════════════════════

  // ── CORE BRAND NAME ── change ONLY these to rebrand the entire app ──

  /// Short display name (Nav bars, headers, dialogs, device home screen)
  static const String appName = 'BrandsMartUSA';

  /// Full legal / marketing name
  static const String appNameFull = 'BrandsMartUSA Protection Plans';

  /// Product brand identifier
  static const String productBrand = 'BrandsMartUSA';

  // ── DERIVED NAMES ── auto-composed from appName / appNameFull ──

  /// AI feature branding
  static const String aiName = '$appName AI';
  static const String aiNameFull = '$appName AI';

  /// Wallet / Payment branding
  static const String walletName = '$appName Wallet';

  /// Protection plan branding
  static const String protectionPlan = 'Protection Plan';
  static const String protectionPlans = 'Protection Plans';
  static const String brandProtectionPlans = appNameFull;
  static const String brandProtection = 'BrandsMartUSA Protection';

  /// Plan tier names (can be overridden per white-label)
  static const String planEssential = 'Essential';
  static const String planPremium = 'Premium';
  static const String planUltimate = 'Ultimate';

  /// Provider identifier used in data models (lowercase appName)
  static const String brandProvider = 'brandsmartusa'; // keep stable for API / data layer
  static const String brandProviderUpper = 'BRANDSMARTUSA'; // keep stable for API / data layer

  /// Plan slugs used in data models (keep stable for API / data layer)
  static const String planEssentialSlug = 'brandsmartusa-essential';
  static const String planPremiumSlug = 'brandsmartusa-premium';
  static const String planUltimateSlug = 'brandsmartusa-ultimate';

  // ══════════════════════════════════════════════════════════════════════════
  //  APP METADATA
  // ══════════════════════════════════════════════════════════════════════════

  static const String appVersion = '1.0.0';

  // ══════════════════════════════════════════════════════════════════════════
  //  SUPPORT / CONTACT
  // ══════════════════════════════════════════════════════════════════════════

  static const String supportEmail = 'support@brandsmartusa.com';
  static const String supportPhone = '1-877-WARRANTY (927-7268)';

  // ══════════════════════════════════════════════════════════════════════════
  //  AI MESSAGES  — used in chat / troubleshoot screens
  // ══════════════════════════════════════════════════════════════════════════

  static const String aiPreparingSuggestions =
      '$aiName is preparing suggestions…';
  static const String aiReviewingDescription =
      '$aiName is reviewing your description and\nidentifying possible root causes.';
  static const String generatedByApp = 'Generated by $appName App';
  static String documentTitle(String title) =>
      '$title - Document from $appName App';

  // ══════════════════════════════════════════════════════════════════════════
  //  PROTECTION PLAN MESSAGES
  // ══════════════════════════════════════════════════════════════════════════

  static const String protectionPlanActivated = '$protectionPlan Activated!';
  static String protectionPlanActiveFor(String assetName) =>
      'Your $protectionPlanLower for $assetName is now active.';
  static const String protectionPlanLower = 'protection plan';
  static const String protectionPlanRenewed = '$protectionPlan Renewed';
  static String premiumPlanProcessed =
      '$planPremium $protectionPlan has been processed';
  static String ultimatePlanRenewed =
      '$planUltimate $protectionPlan has been automatically renewed';
  static const String protectionPlanExpired =
      'Your appliance $protectionPlanLower has expired';
  static const String comprehensivePlansDescription =
      'comprehensive $protectionPlanLower' 's';

  // ══════════════════════════════════════════════════════════════════════════
  //  COMMON ACTIONS
  // ══════════════════════════════════════════════════════════════════════════

  static const String ok = 'OK';
  static const String cancel = 'Cancel';
  static const String save = 'Save';
  static const String delete = 'Delete';
  static const String edit = 'Edit';
  static const String add = 'Add';
  static const String remove = 'Remove';
  static const String search = 'Search';
  static const String filter = 'Filter';
  static const String apply = 'Apply';
  static const String reset = 'Reset';
  static const String confirm = 'Confirm';
  static const String yes = 'Yes';
  static const String no = 'No';
  static const String next = 'Next';
  static const String back = 'Back';
  static const String submit = 'Submit';
  static const String done = 'Done';
  static const String close = 'Close';

  // ══════════════════════════════════════════════════════════════════════════
  //  COMMON MESSAGES
  // ══════════════════════════════════════════════════════════════════════════

  static const String loading = 'Loading...';
  static const String noData = 'No data available';
  static const String error = 'An error occurred';
  static const String success = 'Success';
  static const String retry = 'Retry';
  static const String comingSoon = 'Coming Soon';

  // ══════════════════════════════════════════════════════════════════════════
  //  VALIDATION MESSAGES
  // ══════════════════════════════════════════════════════════════════════════

  static const String required = 'This field is required';
  static const String invalidEmail = 'Please enter a valid email';
  static const String invalidPhone = 'Please enter a valid phone number';
  static const String passwordTooShort =
      'Password must be at least 6 characters';
  static const String passwordsDoNotMatch = 'Passwords do not match';

  // ══════════════════════════════════════════════════════════════════════════
  //  ERROR MESSAGES
  // ══════════════════════════════════════════════════════════════════════════

  static const String networkError =
      'Network error. Please check your connection';
  static const String serverError = 'Server error. Please try again later';
  static const String unknownError = 'An unknown error occurred';

  // ══════════════════════════════════════════════════════════════════════════
  //  ROUTE ERROR MESSAGES
  // ══════════════════════════════════════════════════════════════════════════

  static const String serviceCategoryNotFound = 'Service category not found';
  static const String serviceNotFound = 'Service not found';
  static const String assetNotFound = 'Asset not found';
  static const String planOrAssetNotFound = 'Plan or asset not found';
  static const String requiredDataNotFound = 'Required data not found';
  static const String planDataNotFound = 'Plan data not found';
  static const String dataNotFound = 'Data not found';
  static const String productNotFound = 'Product not found';
  static const String checkoutDataNotFound = 'Checkout data not found';
  static const String orderDataNotFound = 'Order data not found';
  static const String reminderNotFound = 'Reminder not found';
  static const String totalAmountNotProvided = 'Total amount not provided';
  static String routeError(String error) => 'Error: $error';
}

